const dns = require('node:dns').promises;
const net = require('node:net');

const BLOCKED_HOSTS = new Set(['localhost', 'localhost.localdomain']);

function isPrivateIp(ip) {
  if (net.isIPv4(ip)) {
    const p = ip.split('.').map(Number);
    return p[0] === 10 ||
      p[0] === 127 ||
      (p[0] === 169 && p[1] === 254) ||
      (p[0] === 172 && p[1] >= 16 && p[1] <= 31) ||
      (p[0] === 192 && p[1] === 168) ||
      p[0] === 0;
  }
  if (net.isIPv6(ip)) {
    const x = ip.toLowerCase();
    return x === '::1' || x.startsWith('fc') || x.startsWith('fd') || x.startsWith('fe80:') || x === '::';
  }
  return true;
}

async function validatePublicUrl(rawUrl) {
  let normalized = String(rawUrl || '').trim();
  if (!/^https?:\/\//i.test(normalized)) normalized = `https://${normalized}`;
  const url = new URL(normalized);
  if (!['http:', 'https:'].includes(url.protocol)) throw new Error('Only http:// and https:// URLs are supported.');
  if (url.username || url.password) throw new Error('URLs containing credentials are not allowed.');
  if (BLOCKED_HOSTS.has(url.hostname.toLowerCase())) throw new Error('Local or private-network addresses are not allowed.');

  const records = await dns.lookup(url.hostname, { all: true, verbatim: true });
  if (!records.length || records.some(r => isPrivateIp(r.address))) {
    throw new Error('The hostname resolves to a local or private-network address, which is blocked.');
  }
  return url;
}

function stripTags(html) {
  return html
    .replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi, ' ')
    .replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi, ' ')
    .replace(/<noscript\b[^>]*>[\s\S]*?<\/noscript>/gi, ' ')
    .replace(/<[^>]+>/g, ' ')
    .replace(/&nbsp;/gi, ' ')
    .replace(/&amp;/gi, '&')
    .replace(/&quot;/gi, '"')
    .replace(/&#39;/gi, "'")
    .replace(/\s+/g, ' ')
    .trim();
}

function extractAll(html, regex, group = 1) {
  const out = [];
  let m;
  const r = new RegExp(regex.source, regex.flags.includes('g') ? regex.flags : `${regex.flags}g`);
  while ((m = r.exec(html)) && out.length < 100) out.push(m[group]);
  return out.filter(Boolean);
}

function findEvidence(text, patterns, label) {
  const lower = text.toLowerCase();
  for (const p of patterns) {
    const idx = lower.indexOf(p.toLowerCase());
    if (idx >= 0) {
      const start = Math.max(0, idx - 70);
      const end = Math.min(text.length, idx + p.length + 100);
      return `${label}: “…${text.slice(start, end).trim()}…”`;
    }
  }
  return null;
}

function analyseHtml(html, finalUrl, status, contentType) {
  const title = (html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1] || '').replace(/\s+/g, ' ').trim();
  const scripts = extractAll(html, /<script\b[^>]*\bsrc=["']([^"']+)["'][^>]*>/gi);
  const iframes = extractAll(html, /<iframe\b[^>]*\bsrc=["']([^"']+)["'][^>]*>/gi);
  const text = stripTags(html).slice(0, 250000);
  const haystack = `${html}\n${scripts.join('\n')}\n${iframes.join('\n')}`.toLowerCase();

  const interactiveProviders = [
    ['Intercom', ['intercom', 'widget.intercom.io']],
    ['Zendesk', ['zendesk', 'zdassets.com']],
    ['Drift', ['drift.com', 'driftt.com']],
    ['Crisp', ['crisp.chat']],
    ['Tidio', ['tidio', 'code.tidio.co']],
    ['HubSpot chat', ['hubspot.com/conversations', 'hs-scripts.com']],
    ['Freshchat', ['freshchat', 'freshworks.com']],
    ['Ada', ['ada.support', 'ada.cx']],
    ['Chatbase', ['chatbase.co']],
    ['Botpress', ['botpress']],
    ['Voiceflow', ['voiceflow']],
    ['Manychat', ['manychat']]
  ];

  const providerHits = interactiveProviders
    .filter(([, needles]) => needles.some(n => haystack.includes(n)))
    .map(([name]) => name);

  const chatTextEvidence = findEvidence(text, ['chat with us', 'chatbot', 'virtual assistant', 'ai assistant', 'ask our ai', 'powered by ai'], 'Visible page text');
  const disclosureEvidence = findEvidence(
    text,
    [
      'you are interacting with ai',
      'you are chatting with ai',
      'ai-powered assistant',
      'ai assistant',
      'automated assistant',
      'virtual assistant powered by ai',
      'this chatbot uses ai',
      'responses are generated by ai'
    ],
    'Visible disclosure-like text'
  );

  const genAiEvidence = findEvidence(text, ['generated by ai', 'ai-generated', 'created with ai', 'artificial intelligence generated'], 'Visible AI-content label');

  return {
    target: finalUrl,
    fetchedAt: new Date().toISOString(),
    httpStatus: status,
    contentType,
    title,
    pageTextCharsAnalysed: text.length,
    signals: {
      interactiveAI: {
        detected: providerHits.length > 0 || !!chatTextEvidence,
        confidence: providerHits.length > 0 ? 'medium' : chatTextEvidence ? 'low' : 'low',
        evidence: [
          ...providerHits.map(name => `Detected customer-interaction/chat technology indicator: ${name}. This does not prove that the feature uses AI.`),
          ...(chatTextEvidence ? [chatTextEvidence] : [])
        ]
      },
      aiDisclosure: {
        detected: !!disclosureEvidence,
        confidence: disclosureEvidence ? 'medium' : 'low',
        evidence: disclosureEvidence ? [disclosureEvidence] : []
      },
      aiGeneratedContentLabel: {
        detected: !!genAiEvidence,
        confidence: genAiEvidence ? 'medium' : 'low',
        evidence: genAiEvidence ? [genAiEvidence] : []
      }
    },
    limitations: [
      'Only the fetched public HTML response is analysed in this MVP.',
      'JavaScript-rendered UI states, authenticated areas and user-triggered chat flows may not be visible.',
      'A detected chat technology does not prove that the interaction is AI-powered.',
      'Absence of a detected disclosure does not prove that no disclosure exists.',
      'Internal AI use cannot be inferred reliably from a public website.'
    ]
  };
}

async function scanWebsite(rawUrl) {
  const url = await validatePublicUrl(rawUrl);
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 10000);
  try {
    const response = await fetch(url, {
      redirect: 'follow',
      signal: controller.signal,
      headers: {
        'user-agent': 'AIVerifyEU-ReadinessBot/0.1 (+local MVP; evidence-based public page assessment)',
        'accept': 'text/html,application/xhtml+xml;q=0.9,*/*;q=0.1'
      }
    });

    const finalUrl = new URL(response.url);
    // Redirects are re-validated to mitigate redirect-to-private SSRF.
    await validatePublicUrl(finalUrl.toString());

    const type = response.headers.get('content-type') || '';
    if (!type.toLowerCase().includes('text/html') && !type.toLowerCase().includes('application/xhtml+xml')) {
      throw new Error(`The target did not return an HTML page (${type || 'unknown content type'}).`);
    }

    const max = 2_000_000;
    const reader = response.body.getReader();
    let total = 0;
    const chunks = [];
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      total += value.byteLength;
      if (total > max) throw new Error('The page is larger than the 2 MB MVP scan limit.');
      chunks.push(value);
    }
    const merged = new Uint8Array(total);
    let offset = 0;
    for (const chunk of chunks) { merged.set(chunk, offset); offset += chunk.byteLength; }
    const html = new TextDecoder('utf-8', { fatal: false }).decode(merged);
    return analyseHtml(html, finalUrl.toString(), response.status, type);
  } catch (err) {
    if (err.name === 'AbortError') throw new Error('The website scan timed out after 10 seconds.');
    throw err;
  } finally {
    clearTimeout(timeout);
  }
}

module.exports = { scanWebsite, analyseHtml, validatePublicUrl, isPrivateIp };
